using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Drawing.Design;
using System.Globalization;
using System.Security.Permissions;
using System.Text;
using System.Web;
using System.Web.UI;
using System.Web.UI.Design;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.Configuration;
using System.Runtime.InteropServices;
using System.Text.RegularExpressions;
using System.Collections;

namespace Artem.Web.UI.Controls {

    /// <summary>
    /// 
    /// </summary>
    // CAS
    [AspNetHostingPermission(SecurityAction.LinkDemand, Level = AspNetHostingPermissionLevel.Minimal)]
    [AspNetHostingPermission(SecurityAction.InheritanceDemand, Level = AspNetHostingPermissionLevel.Minimal)]
    //
    [ToolboxData("<{0}:GoogleMap runat=\"server\"> </{0}:GoogleMap>")]
    [Designer(typeof(GoogleMapDesigner))]
    public partial class GoogleMap : DataBoundControl, INamingContainer, IPostBackEventHandler {// WebControl

        #region Static Fields ///////////////////////////////////////////////////////////

        public static Unit DefaultHeight = new Unit("480px");
        public static Unit DefaultWidth = new Unit("600px");
        public static int DefaultZoom = 4;

        #endregion

        #region Fields  /////////////////////////////////////////////////////////////////

        IList<string> _actions;
        string _address;
        string _baseCountryCode;
        GoogleMapBehaviour _behaviour = GoogleMapBehaviour.DefaultSet;
        GoogleBounds _bounds;
        ClientScriptHelper _clientScriptProxy;
        string _dataAddressField;
        string _dataLatitudeField;
        string _dataLongitudeField;
        string _dataTextField;
        GoogleMapView _defaultMapView;
        StateCollection<GoogleDirection> _directions;
        EventList _googleEvents;
        bool _insideUpdatePanel;
        bool _isStatic;
        string _key;
        double _latitude;
        double _longitude;
        StateCollection<GoogleMarker> _markers;
        StateCollection<GooglePolygon> _polygons;
        StateCollection<GooglePolyline> _polylines;
        HtmlGenericControl _templateContainer;
        int _zoom = DefaultZoom;
        ZoomPanType _zoomPanType;

        #endregion

        #region Properties //////////////////////////////////////////////////////////////

        /// <summary>
        /// Gets the actions recorder.
        /// </summary>
        /// <value>The actions.</value>
        protected internal IList<string> Actions {
            get {
                if (_actions == null)
                    _actions = new List<string>();
                return _actions;
            }
        }

        /// <summary>
        /// Gets or sets the address.
        /// </summary>
        /// <value>The address.</value>
        [Category("Google")]
        [JsonData]
        public string Address {
            get { return _address; }
            set {
                if (_address != value) {
                    _address = value;
                    _latitude = _longitude = 0;
                }
            }
        }

        /// <summary>
        /// Gets or sets the base country code.
        /// </summary>
        /// <value>The base country code.</value>
        [Category("Google")]
        [JsonData]
        public string BaseCountryCode {
            get { return _baseCountryCode; }
            set { _baseCountryCode = value; }
        }

        /// <summary>
        /// Gets or sets the bound.
        /// </summary>
        /// <value>The bound.</value>
        [Category("Google")]
        public GoogleBounds Bounds {
            get { return _bounds; }
            protected internal set { _bounds = value; }
        }

        /// <summary>
        /// Gets the server control identifier generated by ASP.NET.
        /// </summary>
        /// <value></value>
        /// <returns>The server control identifier generated by ASP.NET.</returns>
        [JsonData]
        public override string ClientID {
            get { return base.ClientID; }
        }

        /// <summary>
        /// Gets the client map ID.
        /// </summary>
        /// <value>The client map ID.</value>
        [Browsable(false)]
        public string ClientMapID {
            get { return this.ClientID; }
        }

        /// <summary>
        /// Gets or sets the client script proxy.
        /// </summary>
        /// <value>The client script proxy.</value>
        internal ClientScriptHelper ClientScriptProxy {
            get { return _clientScriptProxy; }
        }

        /// <summary>
        /// Gets or sets the data address field.
        /// </summary>
        /// <value>The data address field.</value>
        [Category("Google")]
        public string DataAddressField {
            get { return _dataAddressField; }
            set { _dataAddressField = value; }
        }

        /// <summary>
        /// Gets or sets the data latitude field.
        /// </summary>
        /// <value>The data latitude field.</value>
        [Category("Google")]
        public string DataLatitudeField {
            get { return _dataLatitudeField; }
            set { _dataLatitudeField = value; }
        }

        /// <summary>
        /// Gets or sets the data longitude field.
        /// </summary>
        /// <value>The data longitude field.</value>
        [Category("Google")]
        public string DataLongitudeField {
            get { return _dataLongitudeField; }
            set { _dataLongitudeField = value; }
        }

        /// <summary>
        /// Gets or sets the data text field.
        /// </summary>
        /// <value>The data text field.</value>
        [Category("Google")]
        public string DataTextField {
            get { return _dataTextField; }
            set { _dataTextField = value; }
        }

        /// <summary>
        /// Gets or sets the default map view.
        /// </summary>
        /// <value>The default map view.</value>
        [Category("Google")]
        [JsonData]
        public GoogleMapView DefaultMapView {
            get { return _defaultMapView; }
            set { _defaultMapView = value; }
        }

        /// <summary>
        /// Gets the directions.
        /// </summary>
        /// <value>The directions.</value>
        [Browsable(true)]
        [Category("Google")]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [Editor(typeof(CollectionEditor), typeof(UITypeEditor))]
        [PersistenceMode(PersistenceMode.InnerProperty)]
        [JsonData]
        public StateCollection<GoogleDirection> Directions {
            get {
                if (_directions == null) {
                    _directions = new StateCollection<GoogleDirection>();
                    if (this.IsTrackingViewState) _directions.TrackViewState();
                }
                return _directions;
            }
            protected internal set { _directions = value; }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [enable continuous zoom].
        /// </summary>
        /// <value>
        /// 	<c>true</c> if [enable continuous zoom]; otherwise, <c>false</c>.
        /// </value>
        [Category("Google")]
        [JsonData]
        public bool EnableContinuousZoom {
            get { return (_behaviour & GoogleMapBehaviour.ContinuousZoom) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.ContinuousZoom)
                    : (_behaviour & ~GoogleMapBehaviour.ContinuousZoom);
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [double click zoom].
        /// </summary>
        /// <value><c>true</c> if [double click zoom]; otherwise, <c>false</c>.</value>
        [Category("Google")]
        [JsonData]
        public bool EnableDoubleClickZoom {
            get { return (_behaviour & GoogleMapBehaviour.DoubleClickZoom) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.DoubleClickZoom)
                    : (_behaviour & ~GoogleMapBehaviour.DoubleClickZoom);
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [enable dragging].
        /// </summary>
        /// <value><c>true</c> if [enable dragging]; otherwise, <c>false</c>.</value>
        [Category("Google")]
        [JsonData]
        public bool EnableDragging {
            get { return (_behaviour & GoogleMapBehaviour.Dragging) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.Dragging)
                    : (_behaviour & ~GoogleMapBehaviour.Dragging);
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [enable google bar].
        /// </summary>
        /// <value><c>true</c> if [enable google bar]; otherwise, <c>false</c>.</value>
        [Category("Google")]
        [JsonData]
        public bool EnableGoogleBar {
            get { return (_behaviour & GoogleMapBehaviour.GoogleBar) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.GoogleBar)
                    : (_behaviour & ~GoogleMapBehaviour.GoogleBar);
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [enable info window].
        /// </summary>
        /// <value><c>true</c> if [enable info window]; otherwise, <c>false</c>.</value>
        [Category("Google")]
        [JsonData]
        public bool EnableInfoWindow {
            get { return (_behaviour & GoogleMapBehaviour.InfoWindow) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.InfoWindow)
                    : (_behaviour & ~GoogleMapBehaviour.InfoWindow);
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [enable marker manager].
        /// </summary>
        /// <value><c>true</c> if [enable marker manager]; otherwise, <c>false</c>.</value>
        [Category("Google")]
        [JsonData]
        public bool EnableMarkerManager {
            get { return (_behaviour & GoogleMapBehaviour.MarkerManager) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.MarkerManager)
                    : (_behaviour & ~GoogleMapBehaviour.MarkerManager);
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [enable scroll wheel zoom].
        /// </summary>
        /// <value>
        /// 	<c>true</c> if [enable scroll wheel zoom]; otherwise, <c>false</c>.
        /// </value>
        [Category("Google")]
        [JsonData]
        public bool EnableScrollWheelZoom {
            get { return (_behaviour & GoogleMapBehaviour.ScrollWheelZoom) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.ScrollWheelZoom)
                    : (_behaviour & ~GoogleMapBehaviour.ScrollWheelZoom);
            }
        }

        /// <summary>
        /// Gets a list of event handler delegates for the control. This property is read-only.
        /// </summary>
        /// <value></value>
        /// <returns>The list of event handler delegates.</returns>
        public EventList GoogleEvents {
            get {
                if (_googleEvents == null) {
                    _googleEvents = new EventList(this);
                    //if ((this as IStateManager).IsTrackingViewState)
                    //    (_googleEvents as IStateManager).TrackViewState();
                }
                return _googleEvents;
            }
        }

        /// <summary>
        /// Gets or sets the height of the Web server control.
        /// </summary>
        /// <value></value>
        /// <returns>A <see cref="T:System.Web.UI.WebControls.Unit"/> that represents the height of the control. The default is <see cref="F:System.Web.UI.WebControls.Unit.Empty"/>.</returns>
        /// <exception cref="T:System.ArgumentException">The height was set to a negative value.</exception>
        [JsonData]
        public override Unit Height {
            get { return (base.Height != Unit.Empty) ? base.Height : DefaultHeight; }
            set { base.Height = value; }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [inside update panel].
        /// </summary>
        /// <value><c>true</c> if [inside update panel]; otherwise, <c>false</c>.</value>
        [Category("Google")]
        public bool InsideUpdatePanel {
            get { return _insideUpdatePanel; }
            set { _insideUpdatePanel = value; }
        }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is static.
        /// </summary>
        /// <value><c>true</c> if this instance is static; otherwise, <c>false</c>.</value>
        [Category("Google")]
        [JsonData]
        public bool IsStatic {
            get { return _isStatic; }
            set { _isStatic = value; }
        }

        /// <summary>
        /// Gets or sets the key.
        /// </summary>
        /// <value>The key.</value>
        [Category("Google")]
        [DefaultValue("")]
        [Description("The user key obtained from google map api.")]
        [JsonData]
        public string Key {
            get {
                return (_key != null)
                    ? _key : WebConfigurationManager.AppSettings["GoogleMapKey"];
            }
            set { _key = value; }
        }

        /// <summary>
        /// Gets or sets the latitude.
        /// </summary>
        /// <value>The latitude.</value>
        [Category("Google")]
        [Description("")]
        [JsonData]
        public double Latitude {
            get { return _latitude; }
            set { _latitude = value; }
        }

        /// <summary>
        /// Gets or sets the longitude.
        /// </summary>
        /// <value>The longitude.</value>
        [Category("Google")]
        [Description("")]
        [JsonData]
        public double Longitude {
            get { return _longitude; }
            set { _longitude = value; }
        }

        /// <summary>
        /// Gets the markers.
        /// </summary>
        /// <value>The markers.</value>
        [Browsable(true)]
        [Category("Google")]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [Editor(typeof(CollectionEditor), typeof(UITypeEditor))]
        [PersistenceMode(PersistenceMode.InnerProperty)]
        public StateCollection<GoogleMarker> Markers {
            get {
                if (_markers == null) {
                    _markers = new StateCollection<GoogleMarker>();
                    if (this.IsTrackingViewState) _markers.TrackViewState();
                }
                return _markers;
            }
            protected internal set {
                _markers = value;
                if ((_markers != null) && (this.IsTrackingViewState)) {
                    _markers.TrackViewState();
                }
            }
        }

        [Browsable(true)]
        [Category("Google")]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [Editor(typeof(CollectionEditor), typeof(UITypeEditor))]
        [PersistenceMode(PersistenceMode.InnerProperty)]
        public StateCollection<GooglePolygon> Polygons {
            get {
                if (_polygons == null) {
                    _polygons = new StateCollection<GooglePolygon>();
                    if (this.IsTrackingViewState) _polygons.TrackViewState();
                }
                return _polygons;
            }
            protected internal set {
                _polygons = value;
                if ((_polygons != null) && (this.IsTrackingViewState)) {
                    _polygons.TrackViewState();
                }
            }
        }

        /// <summary>
        /// Gets or sets the polylines.
        /// </summary>
        /// <value>The polylines.</value>
        [Browsable(true)]
        [Category("Google")]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [Editor(typeof(CollectionEditor), typeof(UITypeEditor))]
        [PersistenceMode(PersistenceMode.InnerProperty)]
        public StateCollection<GooglePolyline> Polylines {
            get {
                if (_polylines == null) {
                    _polylines = new StateCollection<GooglePolyline>();
                    if (this.IsTrackingViewState) _polylines.TrackViewState();
                }
                return _polylines;
            }
            protected internal set {
                _polylines = value;
                if ((_polylines != null) && (this.IsTrackingViewState)) {
                    _polylines.TrackViewState();
                }
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [show map type control].
        /// </summary>
        /// <value><c>true</c> if [show map type control]; otherwise, <c>false</c>.</value>
        [Category("Google")]
        [JsonData]
        public bool ShowMapTypeControl {
            get { return (_behaviour & GoogleMapBehaviour.MapTypeControl) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.MapTypeControl)
                    : (_behaviour & ~GoogleMapBehaviour.MapTypeControl);
            }
        }

        [Category("Google")]
        [JsonData]
        public bool ShowScaleControl {
            get { return (_behaviour & GoogleMapBehaviour.ScaleControl) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.ScaleControl)
                    : (_behaviour & ~GoogleMapBehaviour.ScaleControl);
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [show traffic].
        /// </summary>
        /// <value><c>true</c> if [show traffic]; otherwise, <c>false</c>.</value>
        [Category("Google")]
        [JsonData]
        public bool ShowTraffic {
            get { return (_behaviour & GoogleMapBehaviour.Traffic) != 0; }
            set {
                _behaviour = value
                    ? (_behaviour | GoogleMapBehaviour.Traffic)
                    : (_behaviour & ~GoogleMapBehaviour.Traffic);
            }
        }

        /// <summary>
        /// Gets the <see cref="T:System.Web.UI.HtmlTextWriterTag"/> value that corresponds to this Web server control. This property is used primarily by control developers.
        /// </summary>
        /// <value></value>
        /// <returns>One of the <see cref="T:System.Web.UI.HtmlTextWriterTag"/> enumeration values.</returns>
        protected override HtmlTextWriterTag TagKey {
            get { return HtmlTextWriterTag.Div; }
        }

        /// <summary>
        /// Gets or sets the width of the Web server control.
        /// </summary>
        /// <value></value>
        /// <returns>A <see cref="T:System.Web.UI.WebControls.Unit"/> that represents the width of the control. The default is <see cref="F:System.Web.UI.WebControls.Unit.Empty"/>.</returns>
        /// <exception cref="T:System.ArgumentException">The width of the Web server control was set to a negative value. </exception>
        [JsonData]
        public override Unit Width {
            get { return (base.Width != Unit.Empty) ? base.Width : DefaultWidth; }
            set { base.Width = value; }
        }

        /// <summary>
        /// Gets or sets the zoom.
        /// </summary>
        /// <value>The zoom.</value>
        [Category("Google")]
        [JsonData]
        public int Zoom {
            get { return _zoom; }
            set { _zoom = value; }
        }

        /// <summary>
        /// Gets or sets the type of the zoom pan.
        /// </summary>
        /// <value>The type of the zoom pan.</value>
        [Category("Google")]
        [JsonData]
        public ZoomPanType ZoomPanType {
            get { return _zoomPanType; }
            set { _zoomPanType = value; }
        }

        #region - Client Events -

        /// <summary>
        /// Gets or sets the on client click.
        /// </summary>
        /// <value>The on client click.</value>
        public string OnClientClick {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.Click)
                    ? GoogleEvents.ClientEvents[EventList.Click] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.Click] = value; }
        }

        /// <summary>
        /// Gets or sets the on client double click.
        /// </summary>
        /// <value>The on client double click.</value>
        public string OnClientDoubleClick {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.DoubleClick)
                    ? GoogleEvents.ClientEvents[EventList.DoubleClick] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.DoubleClick] = value; }
        }

        /// <summary>
        /// Gets or sets the on client drag.
        /// </summary>
        /// <value>The on client drag.</value>
        public string OnClientDrag {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.Drag)
                    ? GoogleEvents.ClientEvents[EventList.Drag] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.Drag] = value; }
        }

        /// <summary>
        /// Gets or sets the on client drag end.
        /// </summary>
        /// <value>The on client drag end.</value>
        public string OnClientDragEnd {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.DragEnd)
                    ? GoogleEvents.ClientEvents[EventList.DragEnd] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.DragEnd] = value; }
        }

        /// <summary>
        /// Gets or sets the on client drag start.
        /// </summary>
        /// <value>The on client drag start.</value>
        public string OnClientDragStart {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.DragStart)
                    ? GoogleEvents.ClientEvents[EventList.DragStart] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.DragStart] = value; }
        }

        /// <summary>
        /// Gets or sets the on client geo location loaded.
        /// </summary>
        /// <value>The on client geo location loaded.</value>
        public string OnClientGeoLocationLoaded {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.GeoLocationLoaded)
                    ? GoogleEvents.ClientEvents[EventList.GeoLocationLoaded] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.GeoLocationLoaded] = value; }
        }

        /// <summary>
        /// Gets or sets the on client info window before close.
        /// </summary>
        /// <value>The on client info window before close.</value>
        public string OnClientInfoWindowBeforeClose {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.InfoWindowBeforeClose)
                    ? GoogleEvents.ClientEvents[EventList.InfoWindowBeforeClose] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.InfoWindowBeforeClose] = value; }
        }

        /// <summary>
        /// Gets or sets the on client info window close.
        /// </summary>
        /// <value>The on client info window close.</value>
        public string OnClientInfoWindowClose {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.InfoWindowClose)
                    ? GoogleEvents.ClientEvents[EventList.InfoWindowClose] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.InfoWindowClose] = value; }
        }

        /// <summary>
        /// Gets or sets the on client info window open.
        /// </summary>
        /// <value>The on client info window open.</value>
        public string OnClientInfoWindowOpen {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.InfoWindowOpen)
                    ? GoogleEvents.ClientEvents[EventList.InfoWindowOpen] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.InfoWindowOpen] = value; }
        }

        /// <summary>
        /// Gets or sets the on client load.
        /// </summary>
        /// <value>The on client load.</value>
        public string OnClientMapLoad {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.MapLoad)
                    ? GoogleEvents.ClientEvents[EventList.MapLoad] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.MapLoad] = value; }
        }

        /// <summary>
        /// Gets or sets the on client map type add.
        /// </summary>
        /// <value>The on client map type add.</value>
        public string OnClientMapTypeAdd {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.MapTypeAdd)
                    ? GoogleEvents.ClientEvents[EventList.MapTypeAdd] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.MapTypeAdd] = value; }
        }

        /// <summary>
        /// Gets or sets the on client map type changed.
        /// </summary>
        /// <value>The on client map type changed.</value>
        public string OnClientMapTypeChanged {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.MapTypeChanged)
                    ? GoogleEvents.ClientEvents[EventList.MapTypeChanged] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.MapTypeChanged] = value; }
        }

        /// <summary>
        /// Gets or sets the on client map type remove.
        /// </summary>
        /// <value>The on client map type remove.</value>
        public string OnClientMapTypeRemove {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.MapTypeRemove)
                    ? GoogleEvents.ClientEvents[EventList.MapTypeRemove] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.MapTypeRemove] = value; }
        }

        /// <summary>
        /// Gets or sets the on client mouse move.
        /// </summary>
        /// <value>The on client mouse move.</value>
        public string OnClientMouseMove {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.MouseMove)
                    ? GoogleEvents.ClientEvents[EventList.MouseMove] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.MouseMove] = value; }
        }

        /// <summary>
        /// Gets or sets the on client mouse over.
        /// </summary>
        /// <value>The on client mouse over.</value>
        public string OnClientMouseOver {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.MouseOver)
                    ? GoogleEvents.ClientEvents[EventList.MouseOver] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.MouseOver] = value; }
        }

        /// <summary>
        /// Gets or sets the on client mouse out.
        /// </summary>
        /// <value>The on client mouse out.</value>
        public string OnClientMouseOut {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.MouseOut)
                    ? GoogleEvents.ClientEvents[EventList.MouseOut] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.MouseOut] = value; }
        }

        /// <summary>
        /// Gets or sets the on client move.
        /// </summary>
        /// <value>The on client move.</value>
        public string OnClientMove {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.Move)
                    ? GoogleEvents.ClientEvents[EventList.Move] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.Move] = value; }
        }

        /// <summary>
        /// Gets or sets the on client move end.
        /// </summary>
        /// <value>The on client move end.</value>
        public string OnClientMoveEnd {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.MoveEnd)
                    ? GoogleEvents.ClientEvents[EventList.MoveEnd] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.MoveEnd] = value; }
        }

        /// <summary>
        /// Gets or sets the on client move start.
        /// </summary>
        /// <value>The on client move start.</value>
        public string OnClientMoveStart {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.MoveStart)
                    ? GoogleEvents.ClientEvents[EventList.MoveStart] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.MoveStart] = value; }
        }

        /// <summary>
        /// Gets or sets the on client overlay add.
        /// </summary>
        /// <value>The on client overlay add.</value>
        public string OnClientOverlayAdd {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.OverlayAdd)
                    ? GoogleEvents.ClientEvents[EventList.OverlayAdd] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.OverlayAdd] = value; }
        }

        /// <summary>
        /// Gets or sets the on client overlay remove.
        /// </summary>
        /// <value>The on client overlay remove.</value>
        public string OnClientOverlayRemove {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.OverlayRemove)
                    ? GoogleEvents.ClientEvents[EventList.OverlayRemove] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.OverlayRemove] = value; }
        }

        /// <summary>
        /// Gets or sets the on client overlays clear.
        /// </summary>
        /// <value>The on client overlays clear.</value>
        public string OnClientOverlaysClear {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.OverlaysClear)
                    ? GoogleEvents.ClientEvents[EventList.OverlaysClear] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.OverlaysClear] = value; }
        }

        /// <summary>
        /// Gets or sets the on client single right click.
        /// </summary>
        /// <value>The on client single right click.</value>
        public string OnClientSingleRightClick {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.SingleRightClick)
                    ? GoogleEvents.ClientEvents[EventList.SingleRightClick] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.SingleRightClick] = value; }
        }

        /// <summary>
        /// Gets or sets the on client zoom end.
        /// </summary>
        /// <value>The on client zoom end.</value>
        public string OnClientZoomEnd {
            get {
                return GoogleEvents.ClientEvents.ContainsKey(EventList.ZoomEnd)
                    ? GoogleEvents.ClientEvents[EventList.ZoomEnd] : null;
            }
            set { GoogleEvents.ClientEvents[EventList.ZoomEnd] = value; }
        }
        #endregion
        #endregion

        #region Events //////////////////////////////////////////////////////////////////

        /// <summary>
        /// Occurs when [click].
        /// </summary>
        public event EventHandler Click {
            add {
                Events.AddHandler(EventList.Click, value);
                GoogleEvents.ServerEvents.Add(EventList.Click);
            }
            remove {
                Events.RemoveHandler(EventList.Click, value);
                GoogleEvents.ServerEvents.Remove(EventList.Click);
            }
        }

        /// <summary>
        /// Occurs when [double click].
        /// </summary>
        public event EventHandler DoubleClick {
            add {
                Events.AddHandler(EventList.DoubleClick, value);
                GoogleEvents.ServerEvents.Add(EventList.DoubleClick);
            }
            remove {
                Events.RemoveHandler(EventList.DoubleClick, value);
                GoogleEvents.ServerEvents.Remove(EventList.DoubleClick);
            }
        }

        /// <summary>
        /// Occurs when [drag].
        /// </summary>
        public event EventHandler Drag {
            add {
                Events.AddHandler(EventList.Drag, value);
                GoogleEvents.ServerEvents.Add(EventList.Drag);
            }
            remove {
                Events.RemoveHandler(EventList.Drag, value);
                GoogleEvents.ServerEvents.Remove(EventList.Drag);
            }
        }

        /// <summary>
        /// Occurs when [drag end].
        /// </summary>
        public event EventHandler DragEnd {
            add {
                Events.AddHandler(EventList.DragEnd, value);
                GoogleEvents.ServerEvents.Add(EventList.DragEnd);
            }
            remove {
                Events.RemoveHandler(EventList.DragEnd, value);
                GoogleEvents.ServerEvents.Remove(EventList.DragEnd);
            }
        }

        /// <summary>
        /// Occurs when [drag start].
        /// </summary>
        public event EventHandler DragStart {
            add {
                Events.AddHandler(EventList.DragStart, value);
                GoogleEvents.ServerEvents.Add(EventList.DragStart);
            }
            remove {
                Events.RemoveHandler(EventList.DragStart, value);
                GoogleEvents.ServerEvents.Remove(EventList.DragStart);
            }
        }

        /// <summary>
        /// Occurs when [geo location loaded].
        /// </summary>
        public event EventHandler GeoLocationLoaded {
            add {
                Events.AddHandler(EventList.GeoLocationLoaded, value);
                GoogleEvents.ServerEvents.Add(EventList.GeoLocationLoaded);
            }
            remove {
                Events.RemoveHandler(EventList.GeoLocationLoaded, value);
                GoogleEvents.ServerEvents.Remove(EventList.GeoLocationLoaded);
            }
        }

        /// <summary>
        /// Occurs when [info window before close].
        /// </summary>
        public event EventHandler InfoWindowBeforeClose {
            add {
                Events.AddHandler(EventList.InfoWindowBeforeClose, value);
                GoogleEvents.ServerEvents.Add(EventList.InfoWindowBeforeClose);
            }
            remove {
                Events.RemoveHandler(EventList.InfoWindowBeforeClose, value);
                GoogleEvents.ServerEvents.Remove(EventList.InfoWindowBeforeClose);
            }
        }

        /// <summary>
        /// Occurs when [info window close].
        /// </summary>
        public event EventHandler InfoWindowClose {
            add {
                Events.AddHandler(EventList.InfoWindowClose, value);
                GoogleEvents.ServerEvents.Add(EventList.InfoWindowClose);
            }
            remove {
                Events.RemoveHandler(EventList.InfoWindowClose, value);
                GoogleEvents.ServerEvents.Remove(EventList.InfoWindowClose);
            }
        }

        /// <summary>
        /// Occurs when [info window open].
        /// </summary>
        public event EventHandler InfoWindowOpen {
            add {
                Events.AddHandler(EventList.InfoWindowOpen, value);
                GoogleEvents.ServerEvents.Add(EventList.InfoWindowOpen);
            }
            remove {
                Events.RemoveHandler(EventList.InfoWindowOpen, value);
                GoogleEvents.ServerEvents.Remove(EventList.InfoWindowOpen);
            }
        }

        /// <summary>
        /// Occurs when [map load].
        /// </summary>
        public event EventHandler MapLoad {
            add {
                Events.AddHandler(EventList.MapLoad, value);
                GoogleEvents.ServerEvents.Add(EventList.MapLoad);
            }
            remove {
                Events.RemoveHandler(EventList.MapLoad, value);
                GoogleEvents.ServerEvents.Remove(EventList.MapLoad);
            }
        }

        /// <summary>
        /// Occurs when [map type add].
        /// </summary>
        public event EventHandler MapTypeAdd {
            add {
                Events.AddHandler(EventList.MapTypeAdd, value);
                GoogleEvents.ServerEvents.Add(EventList.MapTypeAdd);
            }
            remove {
                Events.RemoveHandler(EventList.MapTypeAdd, value);
                GoogleEvents.ServerEvents.Remove(EventList.MapTypeAdd);
            }
        }

        /// <summary>
        /// Occurs when [map type changed].
        /// </summary>
        public event EventHandler MapTypeChanged {
            add {
                Events.AddHandler(EventList.MapTypeChanged, value);
                GoogleEvents.ServerEvents.Add(EventList.MapTypeChanged);
            }
            remove {
                Events.RemoveHandler(EventList.MapTypeChanged, value);
                GoogleEvents.ServerEvents.Remove(EventList.MapTypeChanged);
            }
        }

        /// <summary>
        /// Occurs when [map type remove].
        /// </summary>
        public event EventHandler MapTypeRemove {
            add {
                Events.AddHandler(EventList.MapTypeRemove, value);
                GoogleEvents.ServerEvents.Add(EventList.MapTypeRemove);
            }
            remove {
                Events.RemoveHandler(EventList.MapTypeRemove, value);
                GoogleEvents.ServerEvents.Remove(EventList.MapTypeRemove);
            }
        }

        /// <summary>
        /// Occurs when [mouse move].
        /// </summary>
        public event EventHandler MouseMove {
            add {
                Events.AddHandler(EventList.MouseMove, value);
                GoogleEvents.ServerEvents.Add(EventList.MouseMove);
            }
            remove {
                Events.RemoveHandler(EventList.MouseMove, value);
                GoogleEvents.ServerEvents.Remove(EventList.MouseMove);
            }
        }

        /// <summary>
        /// Occurs when [mouse out].
        /// </summary>
        public event EventHandler MouseOut {
            add {
                Events.AddHandler(EventList.MouseOut, value);
                GoogleEvents.ServerEvents.Add(EventList.MouseOut);
            }
            remove {
                Events.RemoveHandler(EventList.MouseOut, value);
                GoogleEvents.ServerEvents.Remove(EventList.MouseOut);
            }
        }

        /// <summary>
        /// Occurs when [mouse over].
        /// </summary>
        public event EventHandler MouseOver {
            add {
                Events.AddHandler(EventList.MouseOver, value);
                GoogleEvents.ServerEvents.Add(EventList.MouseOver);
            }
            remove {
                Events.RemoveHandler(EventList.MouseOver, value);
                GoogleEvents.ServerEvents.Remove(EventList.MouseOver);
            }
        }

        /// <summary>
        /// Occurs when [move].
        /// </summary>
        public event EventHandler Move {
            add {
                Events.AddHandler(EventList.Move, value);
                GoogleEvents.ServerEvents.Add(EventList.Move);
            }
            remove {
                Events.RemoveHandler(EventList.Move, value);
                GoogleEvents.ServerEvents.Remove(EventList.Move);
            }
        }

        /// <summary>
        /// Occurs when [move end].
        /// </summary>
        public event EventHandler MoveEnd {
            add {
                Events.AddHandler(EventList.MoveEnd, value);
                GoogleEvents.ServerEvents.Add(EventList.MoveEnd);
            }
            remove {
                Events.RemoveHandler(EventList.MoveEnd, value);
                GoogleEvents.ServerEvents.Remove(EventList.MoveEnd);
            }
        }

        /// <summary>
        /// Occurs when [move start].
        /// </summary>
        public event EventHandler MoveStart {
            add {
                Events.AddHandler(EventList.MoveStart, value);
                GoogleEvents.ServerEvents.Add(EventList.MoveStart);
            }
            remove {
                Events.RemoveHandler(EventList.MoveStart, value);
                GoogleEvents.ServerEvents.Remove(EventList.MoveStart);
            }
        }

        /// <summary>
        /// Occurs when [overlay add].
        /// </summary>
        public event EventHandler OverlayAdd {
            add {
                Events.AddHandler(EventList.OverlayAdd, value);
                GoogleEvents.ServerEvents.Add(EventList.OverlayAdd);
            }
            remove {
                Events.RemoveHandler(EventList.OverlayAdd, value);
                GoogleEvents.ServerEvents.Remove(EventList.OverlayAdd);
            }
        }

        /// <summary>
        /// Occurs when [overlay remove].
        /// </summary>
        public event EventHandler OverlayRemove {
            add {
                Events.AddHandler(EventList.OverlayRemove, value);
                GoogleEvents.ServerEvents.Add(EventList.OverlayRemove);
            }
            remove {
                Events.RemoveHandler(EventList.OverlayRemove, value);
                GoogleEvents.ServerEvents.Remove(EventList.OverlayRemove);
            }
        }

        /// <summary>
        /// Occurs when [overlays clear].
        /// </summary>
        public event EventHandler OverlaysClear {
            add {
                Events.AddHandler(EventList.OverlaysClear, value);
                GoogleEvents.ServerEvents.Add(EventList.OverlaysClear);
            }
            remove {
                Events.RemoveHandler(EventList.OverlaysClear, value);
                GoogleEvents.ServerEvents.Remove(EventList.OverlaysClear);
            }
        }

        /// <summary>
        /// Occurs when [single right click].
        /// </summary>
        public event EventHandler SingleRightClick {
            add {
                Events.AddHandler(EventList.SingleRightClick, value);
                GoogleEvents.ServerEvents.Add(EventList.SingleRightClick);
            }
            remove {
                Events.RemoveHandler(EventList.SingleRightClick, value);
                GoogleEvents.ServerEvents.Remove(EventList.SingleRightClick);
            }
        }

        /// <summary>
        /// Occurs when [zoom end].
        /// </summary>
        public event EventHandler ZoomEnd {
            add {
                Events.AddHandler(EventList.ZoomEnd, value);
                GoogleEvents.ServerEvents.Add(EventList.ZoomEnd);
            }
            remove {
                Events.RemoveHandler(EventList.ZoomEnd, value);
                GoogleEvents.ServerEvents.Remove(EventList.ZoomEnd);
            }
        }
        #endregion

        #region Construct  //////////////////////////////////////////////////////////////

        /// <summary>
        /// Initializes a new instance of the <see cref="GoogleMap"/> class.
        /// </summary>
        public GoogleMap() {
            _clientScriptProxy = new ClientScriptHelper(this);
        }
        #endregion

        #region Methods /////////////////////////////////////////////////////////////////

        /// <summary>
        /// Called by the ASP.NET page framework to notify server controls that use composition-based implementation to create any child controls they contain in preparation for posting back or rendering.
        /// </summary>
        protected override void CreateChildControls() {
            base.CreateChildControls();
            ////
            //HtmlGenericControl mapPane = new HtmlGenericControl("div");
            //mapPane.Attributes["class"] = this.CssClass;
            //mapPane.ID = "Map";
            //mapPane.Style[HtmlTextWriterStyle.Width] = this.Width.ToString();
            //mapPane.Style[HtmlTextWriterStyle.Height] = this.Height.ToString();
            //this.Controls.Add(mapPane);
            //
            _templateContainer = new HtmlGenericControl("div");
            _templateContainer.ID = "Templates";
            _templateContainer.Style[HtmlTextWriterStyle.Display] = "none";
            this.Controls.Add(_templateContainer);
            //
            this.ClearChildViewState();
        }

        /// <summary>
        /// Loads the state of the google map.
        /// </summary>
        /// <param name="state">The state.</param>
        protected virtual void LoadGoogleMapState(string state) {
            if (!string.IsNullOrEmpty(state)) {
                this.Markers.Clear();
                JsonSerializer<GoogleMap>.Deserialize(state, this);
            }
        }

        /// <summary>
        /// Raises the <see cref="E:System.Web.UI.Control.Init"/> event.
        /// </summary>
        /// <param name="e">An <see cref="T:System.EventArgs"/> object that contains the event data.</param>
        protected override void OnInit(EventArgs e) {
            base.OnInit(e);
            // initialize from saved state
            LoadGoogleMapState(this.Page.Request[this.ClientID + "_State"]);
        }

        /// <summary>
        /// Raises the <see cref="E:System.Web.UI.Control.PreRender"/> event.
        /// </summary>
        /// <param name="e">An <see cref="T:System.EventArgs"/> object that contains the event data.</param>
        protected override void OnPreRender(EventArgs e) {
            base.OnPreRender(e);

            //
            ClientScriptProxy.RegisterClientScriptInclude("maps.google.com",
                string.Format("http://maps.google.com/maps?file=api&v=2&key={0}", Key));
#if DEBUG
            ClientScriptProxy.RegisterClientScriptResource(
                "Artem.Web.UI.Controls.Scripts.GoogleMap3.debug.js");
#else
            ClientScriptProxy.RegisterClientScriptResource(
                "Artem.Web.UI.Controls.Scripts.GoogleMap3.js");
#endif
            string key = "Artem.Web.GoogleMap:" + this.ClientID;
            ClientScriptProxy.RegisterStartupScript(key, RenderMapScript(), true);
        }

        /// <summary>
        /// Renders the contents of the control to the specified writer. This method is used primarily by control developers.
        /// </summary>
        /// <param name="writer">A <see cref="T:System.Web.UI.HtmlTextWriter"/> that represents the output stream to render HTML content on the client.</param>
        protected override void RenderContents(HtmlTextWriter writer) {
            // KEEP THIS EMPTY
        }

        /// <summary>
        /// Renders the HTML closing tag of the control into the specified writer. This method is used primarily by control developers.
        /// </summary>
        /// <param name="writer">A <see cref="T:System.Web.UI.HtmlTextWriter"/> that represents the output stream to render HTML content on the client.</param>
        public override void RenderEndTag(HtmlTextWriter writer) {
            base.RenderEndTag(writer);

            // must be outside the map div otherwise Google API script will remove it
            _templateContainer.RenderControl(writer);
            // state bag
            string stateBagId = this.ClientID + "_State";
            writer.AddAttribute(HtmlTextWriterAttribute.Id, stateBagId);
            writer.AddAttribute(HtmlTextWriterAttribute.Name, stateBagId);
            writer.AddAttribute(HtmlTextWriterAttribute.Type, "hidden");
            writer.RenderBeginTag(HtmlTextWriterTag.Input);
            writer.RenderEndTag();
        }

        /// <summary>
        /// Toes the json.
        /// </summary>
        /// <returns></returns>
        protected string ToJsonString() {

            string json = JsonSerializer<GoogleMap>.Serialize(this);
            string width = string.Format("\"{0}\"", this.Width.ToString());
            string height = string.Format("\"{0}\"", this.Height.ToString());
            json = Regex.Replace(json, @"(?<=""Width"":)(\{[^\}]*\})", width, JsUtil.DefaultRegexOptions);
            json = Regex.Replace(json, @"(?<=""Height"":)(\{[^\}]*\})", height, JsUtil.DefaultRegexOptions);
            return json;
        }

        #region - Map Script -

        /// <summary>
        /// Renders the init script.
        /// </summary>
        /// <returns></returns>
        protected virtual string RenderMapScript() {

            string id = this.ClientID;
            string action;
            StringBuilder script = new StringBuilder();
            // construct
            script
                .AppendFormat("var {0} = new Artem.Web.GoogleMap({1});", id, this.ToJsonString())
                .AppendLine();
            // map's actions
            for (int i = 0; i < this.Actions.Count; i++) {
                action = this.Actions[i];
                script
                    .AppendFormat("{0}.addAction({1});", id, JsUtil.Encode(action))
                    .AppendLine();
            }
            // markers
            string config;
            GoogleMarker marker;
            for (int i = 0; i < this.Markers.Count; i++) {
                marker = this.Markers[i];
                config = marker.ToJsonString();
                config = config.Replace("INDEX", i.ToString());
                config = Regex.Replace(config, @"(?<event>marker_event[^""]*)",
                    delegate(Match m) {
                        return this.Page.ClientScript.GetPostBackEventReference(this, m.Groups["event"].Value);
                    },
                    JsUtil.DefaultRegexOptions
                );
                config = Regex.Replace(config, @"(""ImageUrl"":"")([^""]*)""",
                    delegate(Match m) {
                        return string.Format("{0}{1}\"", m.Groups[1].Value, ResolveUrl(m.Groups[2].Value));
                    },
                    JsUtil.DefaultRegexOptions
                );
                config = Regex.Replace(config, @"(""ShadowUrl"":"")([^""]*)""",
                    delegate(Match m) {
                        return string.Format("{0}{1}\"", m.Groups[1].Value, ResolveUrl(m.Groups[2].Value));
                    },
                    JsUtil.DefaultRegexOptions
                );
                script
                    .AppendFormat("{0}.addMarker({1});", id, config)
                    .AppendLine();
                // info window content template
                if (marker.InfoWindowContent != null) {
                    GoogleMarker.TemplateContainer container = new GoogleMarker.TemplateContainer();
                    container.ID = string.Format("Marker{0}Content", i.ToString());
                    marker.InfoWindowContent.InstantiateIn(container);
                    _templateContainer.Controls.Add(container);
                    script.AppendFormat("{0}.Markers[{1}].OpenWindowContent = '{2}';", id, i, container.ClientID);
                }
                // marker's actions
                for (int j = 0; j < marker.Actions.Count; j++) {// string action in this.Markers[i].Actions) {
                    action = marker.Actions[j];
                    action = string.Format(action, id, i);
                    script
                        .AppendFormat("{0}.addAction({1});", id, JsUtil.Encode(action))
                        .AppendLine();
                }
            }
            // directions
            GoogleDirection dir;
            for (int i = 0; i < this.Directions.Count; i++) {
                dir = this.Directions[i];
                script
                    .AppendFormat("{0}.addDirection({1});", id, dir.ToJsonString())
                    .AppendLine();
                // direction's actions
                for (int j = 0; j < dir.Actions.Count; j++) {
                    action = dir.Actions[j];
                    action = string.Format(action, id, i);
                    script
                        .AppendFormat("{0}.addAction({1});", id, JsUtil.Encode(action))
                        .AppendLine();
                }
            }
            // polylines
            GooglePolyline line;
            for (int i = 0; i < this.Polylines.Count; i++) {
                line = this.Polylines[i];
                script
                    .AppendFormat("{0}.addPolyline({1});", id, line.ToJsonString())
                    .AppendLine();
                // polyline's actions
                for (int j = 0; j < line.Actions.Count; j++) {
                    action = line.Actions[j];
                    action = string.Format(action, id, i);
                    script
                        .AppendFormat("{0}.addAction({1});", id, JsUtil.Encode(action))
                        .AppendLine();
                }
            }
            // polygons
            GooglePolygon pg;
            for (int i = 0; i < this.Polygons.Count; i++) {
                pg = this.Polygons[i];
                script
                    .AppendFormat("{0}.addPolygon({1});", id, pg.ToJsonString())
                    .AppendLine();
                // polygon's actions
                for (int j = 0; j < pg.Actions.Count; j++) {
                    action = pg.Actions[j];
                    action = string.Format(action, id, i);
                    script
                        .AppendFormat("{0}.addAction({1});", id, JsUtil.Encode(action))
                        .AppendLine();
                }
            }
            // load
            script.AppendFormat("{0}.load();", id).AppendLine();
            #region Obsolete (ensure works fine without this!?)
            //if (ClientScriptProxy.IsAjaxEnabled()) {
            //    script
            //        .Append("Sys.Application.add_init(function() {")
            //        .AppendFormat("{0}.load();", id)
            //        .Append("});")
            //        .AppendLine();
            //}
            //else {
            //    script
            //        .AppendLine("if(document.getElementById && document.createTextNode)")
            //        .AppendLine("{")
            //        .AppendLine("if (window.addEventListener)")
            //        .AppendLine("window.addEventListener(\"load\", function(){" + id + ".load();}, false);")
            //        .AppendLine("else if (window.attachEvent)")
            //        .AppendLine("window.attachEvent(\"onload\", function(){" + id + ".load();}, false);")
            //        .AppendLine("}")
            //        .AppendLine("else")
            //        .AppendFormat("{0}.load();", id)
            //        .AppendLine();
            //}
            #endregion
            return script.ToString();
        }
        #endregion

        #region - Data Bind -

        protected override void PerformDataBinding(IEnumerable data) {
            base.PerformDataBinding(data);
            if (data != null) {
                bool hasAddressDataField = !string.IsNullOrEmpty(DataAddressField);
                bool hasLatitudeDataField = !string.IsNullOrEmpty(DataLatitudeField);
                bool hasLongitudeDataField = !string.IsNullOrEmpty(DataLongitudeField);
                bool hasTextDataField = !string.IsNullOrEmpty(DataTextField);
                GoogleMarker marker;
                foreach (object dataItem in data) {
                    marker = new GoogleMarker();
                    if (hasAddressDataField)
                        marker.Address = DataBinder.Eval(dataItem, DataAddressField, "");
                    if (hasLatitudeDataField)
                        marker.Latitude = JsUtil.ToDouble(DataBinder.Eval(dataItem, DataLatitudeField, ""));
                    if (hasLongitudeDataField)
                        marker.Longitude = JsUtil.ToDouble(DataBinder.Eval(dataItem, DataLongitudeField, ""));
                    if (hasTextDataField)
                        marker.Text = DataBinder.Eval(dataItem, DataTextField, "");
                    this.Markers.Add(marker);
                }
            }
        }

        /// <summary>
        /// Retrieves data from the associated data source.
        /// </summary>
        protected override void PerformSelect() {

            if (IsBoundUsingDataSourceID)
                this.OnDataBinding(EventArgs.Empty);
            GetData().Select(
                CreateDataSourceSelectArguments(),
                this.OnDataSourceViewSelectCallback);
            // The PerformDataBinding method has completed.
            RequiresDataBinding = false;
            MarkAsDataBound();
            // Raise the DataBound event.
            OnDataBound(EventArgs.Empty);
        }

        /// <summary>
        /// Called when [data source view select callback].
        /// </summary>
        /// <param name="retrievedData">The retrieved data.</param>
        void OnDataSourceViewSelectCallback(IEnumerable retrievedData) {

            if (IsBoundUsingDataSourceID)
                OnDataBinding(EventArgs.Empty);
            PerformDataBinding(retrievedData);
        }
        #endregion

        #region - Actions -

        /// <summary>
        /// Opens a simple info window at the given point. 
        /// Pans the map such that the opened info window is fully visible. 
        /// The content of the info window is given as a DOM node.
        /// </summary>
        /// <param name="point">The point.</param>
        /// <param name="node">The node.</param>
        /// <param name="options">The options.</param>
        public void OpenInfoWindow(GoogleLocation point, string node, string options) {

            this.Actions.Add(
                string.Format("{0}.openInfoWindow(new GLatLng({1}, {2}), {3} {4});",
                    this.ClientID,
                    JsUtil.Encode(this.Latitude),
                    JsUtil.Encode(this.Longitude),
                    JsUtil.Encode(node),
                    string.IsNullOrEmpty(options) ? string.Empty : "," + JsUtil.Encode(options)
                )
            );
        }

        /// <summary>
        /// Opens a simple info window at the given point. 
        /// Pans the map such that the opened info window is fully visible. 
        /// The content of the info window is given as HTML text.
        /// </summary>
        /// <param name="point">The point.</param>
        /// <param name="text">The text.</param>
        /// <param name="options">The options.</param>
        public void OpenInfoWindowHtml(GoogleLocation point, string text, string options) {

            this.Actions.Add(
                string.Format("{0}.openInfoWindowHtml(new GLatLng({1}, {2}), {3} {4});",
                    this.ClientID,
                    JsUtil.Encode(this.Latitude),
                    JsUtil.Encode(this.Longitude),
                    JsUtil.Encode(text),
                    string.IsNullOrEmpty(options) ? string.Empty : "," + JsUtil.Encode(options)
                )
            );
        }

        /// <summary>
        /// Changes the center point of the map to the given point. 
        /// If the point is already visible in the current map view, change the center in a smooth animation.
        /// </summary>
        /// <param name="center">The center.</param>
        public void PanTo(GoogleLocation center) {

            this.Actions.Add(
                string.Format("{0}.panTo(new GLatLng({1}, {2}));",
                    this.ClientID,
                    JsUtil.Encode(this.Latitude),
                    JsUtil.Encode(this.Longitude)
                )
            );
        }

        /// <summary>
        /// Starts a pan animation by the given distance in pixels.
        /// </summary>
        /// <param name="distance">The distance.</param>
        public void PanBy(int distance) {
            this.Actions.Add(
                string.Format("{0}.panBy({1});", this.ClientID, distance));
        }

        /// <summary>
        /// Starts a pan animation by half the width of the map in the indicated directions. 
        /// +1 is right and down, -1 is left and up, respectively.
        /// </summary>
        /// <param name="dx">The dx.</param>
        /// <param name="dy">The dy.</param>
        public void PanDirection(int dx, int dy) {
            this.Actions.Add(
                string.Format("{0}.panDirection({1}, {2});", this.ClientID, dx, dy));
        }

        /// <summary>
        /// Increments zoom level by one.
        /// </summary>
        public void ZoomIn() {
            this.Actions.Add(string.Format("{0}.zoomIn();", this.ClientID));
        }

        /// <summary>
        /// Decrements zoom level by one.
        /// </summary>
        public void ZoomOut() {
            this.Actions.Add(string.Format("{0}.zoomOut();", this.ClientID));
        }
        #endregion

        #region - IPostBackEventHandler -

        /// <summary>
        /// When implemented by a class, enables a server control to process an event raised when a form is posted to the server.
        /// </summary>
        /// <param name="eventArgument">A <see cref="T:System.String"/> that represents an optional event argument to be passed to the event handler.</param>
        void IPostBackEventHandler.RaisePostBackEvent(string eventArgument) {

            if (!string.IsNullOrEmpty(eventArgument)) {
                string[] args = eventArgument.Split('$');
                if (args.Length > 0) {
                    switch (args[0]) {
                        case "marker_event":
                            if (args.Length > 2) {
                                int index;
                                if (int.TryParse(args[1], out index))
                                    this.Markers[index].FireEvent(args[2]);
                            }
                            break;
                        case "map_event":
                            FireEvent(args[1]);
                            break;
                    }
                }
            }
        }

        /// <summary>
        /// Fires the event.
        /// </summary>
        /// <param name="key">The key.</param>
        protected internal virtual void FireEvent(string key) {

            Delegate handler = null;
            switch (key) {
                case EventList.Click:
                    handler = Events[EventList.Click];
                    break;
                case EventList.DoubleClick:
                    handler = Events[EventList.DoubleClick];
                    break;
                case EventList.Drag:
                    handler = Events[EventList.Drag];
                    break;
                case EventList.DragEnd:
                    handler = Events[EventList.DragEnd];
                    break;
                case EventList.DragStart:
                    handler = Events[EventList.DragStart];
                    break;
                case EventList.GeoLocationLoaded:
                    handler = Events[EventList.GeoLocationLoaded];
                    break;
                case EventList.InfoWindowBeforeClose:
                    handler = Events[EventList.InfoWindowBeforeClose];
                    break;
                case EventList.InfoWindowClose:
                    handler = Events[EventList.InfoWindowClose];
                    break;
                case EventList.InfoWindowOpen:
                    handler = Events[EventList.InfoWindowOpen];
                    break;
                case EventList.MapLoad:
                    handler = Events[EventList.MapLoad];
                    break;
                case EventList.MapTypeAdd:
                    handler = Events[EventList.MapTypeAdd];
                    break;
                case EventList.MapTypeChanged:
                    handler = Events[EventList.MapTypeChanged];
                    break;
                case EventList.MapTypeRemove:
                    handler = Events[EventList.MapTypeRemove];
                    break;
                case EventList.MouseMove:
                    handler = Events[EventList.MouseMove];
                    break;
                case EventList.MouseOut:
                    handler = Events[EventList.MouseOut];
                    break;
                case EventList.MouseOver:
                    handler = Events[EventList.MouseOver];
                    break;
                case EventList.Move:
                    handler = Events[EventList.Move];
                    break;
                case EventList.MoveEnd:
                    handler = Events[EventList.MoveEnd];
                    break;
                case EventList.MoveStart:
                    handler = Events[EventList.MoveStart];
                    break;
                case EventList.OverlayAdd:
                    handler = Events[EventList.OverlayAdd];
                    break;
                case EventList.OverlayRemove:
                    handler = Events[EventList.OverlayRemove];
                    break;
                case EventList.OverlaysClear:
                    handler = Events[EventList.OverlaysClear];
                    break;
                case EventList.SingleRightClick:
                    handler = Events[EventList.SingleRightClick];
                    break;
                case EventList.ZoomEnd:
                    handler = Events[EventList.ZoomEnd];
                    break;
            }
            if (handler != null) handler.DynamicInvoke(this, EventArgs.Empty);
        }
        #endregion
        #endregion
    }
}